### DISCUSSION TITLE
How to configure Github Action with GIGET_AUTH

### DISCUSSION THREAD

**Discussion by martijnhalekor** [unjs/community#43] [General]
I am setting up a GitHub Action which runs tests when a PR is created. I am however stuck in the `install` step as my Nuxt project is depending on a layer, hosted as a private GitHub repository. I have added GIGET_AUTH as a secret in the repo settings on github, but the install step returns the following error:
`Failed to download https://api.github.com/repos/kraftersnl/krafters-ui/tarball/main: 404 Not Found`

I have no issue with the Nuxt layer setup when deploying our app, but I can't get the GitHub Action working 😐 
My github action:

```yml
name: Run unit tests

on:
  pull_request:
    branches: [main]

jobs:
  pull-request-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm test
```

Am I missing an obvious confguration setting or is the `GIGET_AUTH` token not supported in GitHub Actions?
Thanks in advance! 🙏

**Comment by martijnhalekor** [comment]
I figured it out! I simply had to add the env property, referring to the secret I stored at GitHub. See example below for the missing piece of the puzzle.

```yml
- name: Install packages
  run: npm ci
  env:
    GIGET_AUTH: ${{ secrets.GIGET_AUTH }}
```
